// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK2Cnpd3pd4F0u5nuMenEZGAqY0pa6mzQ',
    appId: '1:527821342835:web:3d19fe1bf1ead735c6c206',
    messagingSenderId: '527821342835',
    projectId: 'fyn-bank-app',
    authDomain: 'fyn-bank-app.firebaseapp.com',
    storageBucket: 'fyn-bank-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzWNtbJxT4KnYdN-EFZZbiXa73fczHlY',
    appId: '1:527821342835:android:d1dc493c02bcedcac6c206',
    messagingSenderId: '527821342835',
    projectId: 'fyn-bank-app',
    storageBucket: 'fyn-bank-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhqBN1eAosYt2gh0E7SmFR4OBO3NhZWA',
    appId: '1:527821342835:ios:b4f9a3023c2b1760c6c206',
    messagingSenderId: '527821342835',
    projectId: 'fyn-bank-app',
    storageBucket: 'fyn-bank-app.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );
}
